backend:
  name: github
  repo: 956productions/956productions.github.io   # Path to your Github repository
  branch: main   # Branch to update
  base_url: https://ninefivesix-oauth.herokuapp.com
media_folder: 'img'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Show TOC?', name: 'toc', widget: 'boolean', default: false }
      - { label: 'Redirect?', name: 'redirect', widget: 'string' }
      - { label: 'Layout', name: 'layout', widget: 'select', options: ["default","front"], default: "default" }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
  - name: 'pages'
    label: 'Static Page'
    folder: '/'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Show TOC?', name: 'toc', widget: 'boolean', default: false }
      - { label: 'Redirect?', name: 'redirect', widget: 'string' }
      - { label: 'Layout', name: 'layout', widget: 'select', options: ["default","front"], default: "default" }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
  - name: 'results'
    label: 'Results Page'
    folder: 'results/'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Show TOC?', name: 'toc', widget: 'boolean', default: false }
      - { label: 'Redirect?', name: 'redirect', widget: 'string' }
      - { label: 'Layout', name: 'layout', widget: 'select', options: ["default","front"], default: "default" }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }